import fs from 'node:fs';
import path from 'node:path';
import type { NextConfig } from 'next';

type Redirect = { source: string; destination: string };

// WordPress upload URLs, originals and resized copies, to the downloaded file
// in public/images/ (generated by scripts/build-content.mjs).
const uploadRedirects: Redirect[] = JSON.parse(
  fs.readFileSync(path.join(process.cwd(), 'content/upload-redirects.json'), 'utf8'),
);

// Live WordPress URLs outside the new route list, with targets approved by
// Steve (NOTES_FOR_STEVE.md, step 1).
const legacyRedirects: Redirect[] = [
  { source: '/category/blog/', destination: '/blog/' },
  { source: '/category/blog/page/:page/', destination: '/blog/' },
  { source: '/category/case-studies/', destination: '/case-studies/' },
  { source: '/category/uncategorised/', destination: '/' },
  { source: '/tag/floor-restoration-london/', destination: '/services/floor-restoration/' },
  { source: '/tag/metal-polishing-london/', destination: '/services/metal-polishing/' },
  { source: '/tag/metal-polishing-in-london/', destination: '/services/metal-polishing/' },
  { source: '/tag/building-restorations-london/', destination: '/services/building-restoration/' },
  { source: '/tag/building-restorations-in-london/', destination: '/services/building-restoration/' },
  { source: '/tag/restoration-services/', destination: '/services/' },
  { source: '/tag/restoration-services-london/', destination: '/services/' },
  { source: '/tag/complete-restoration-solutions/', destination: '/services/' },
  { source: '/tag/uk-building-conservation/', destination: '/services/' },
  { source: '/author/addrankone/', destination: '/' },
  { source: '/author/federation/', destination: '/' },
  { source: '/esm_testimonials/test1/', destination: '/' },
  { source: '/site-map/', destination: '/' },
  { source: '/feed/', destination: '/blog/' },
  { source: '/comments/feed/', destination: '/blog/' },
  { source: '/case-studies/feed/', destination: '/blog/' },
];

const nextConfig: NextConfig = {
  // Every WordPress URL ends in a slash; keep them identical.
  trailingSlash: true,
  async redirects() {
    // 301 rather than Next.js's default 308 for permanent redirects, as the brief asks.
    return [...uploadRedirects, ...legacyRedirects].map((r) => ({ ...r, statusCode: 301 as const }));
  },
};

export default nextConfig;
